Message.create(content: "Hello, world!")
Message.create(content: "Welcome to our app!")
Message.create(content: "Greetings, traveler!")
Message.create(content: "Hey there, how can I help you?")
Message.create(content: "Hello from the other side!")